server:
   port: 8080
spring:
   application:
      name: gateway-server

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true

zuul:
  routes:
    product-service:
      path: /product-service/**
      serviceId: product-service
    user-service:
      path: /user-service/**
      serviceId: user-service
      #url: http://localhost:8081/
ribbon:
 eureka:
   enabled: false