server:
   port: 8080
spring:
   application:
      name: gateway-server

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true

zuul:
  routes:
    product-service:
      path: /product-service/**
      url: http://localhost:8082/
    user-service:
      path: /user-service/**
      url: http://localhost:8081/
    auth-service:
      path: /auth-service/**
      url: http://localhost:8083/
ribbon:
 eureka:
   enabled: false