server:
  port: 8083

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jpatest
    username: test
    password: 123456
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
      schema: jpatest
  jpa:
    properties:
      hibernate.default_schema: jpatest
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update

  application:
    name: auth-service

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      check-token-url: http://localhost:8080/oauth/check-token
      scope: read,write
      auto-approve-scopes: '.*'
